DROP TABLE IF EXISTS public."EMPLOYEES";

CREATE TABLE public."EMPLOYEES"
(
  "ID"         UUID      NOT NULL
    CONSTRAINT "EMPLOYEES_pkey"
    PRIMARY KEY,
  "FIRST_NAME" VARCHAR   NOT NULL,
  "LAST_NAME"  VARCHAR   NOT NULL,
  "BIRTH_DATE" TIMESTAMP NOT NULL,
  "COMPANY_ID" UUID      NOT NULL
    CONSTRAINT FK_COMPANY
    REFERENCES "COMPANIES"
);
